name: Continuous Integration

on:
  push:
    branches: [ main ]

jobs:
  Test:

    runs-on: ubuntu-latest

    container:
      image: joezuntz/txpipe-auto

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Import firecrown
      run: |
        python -c "import faulthandler; faulthandler.enable(); import camb"


    - name: ls
      if: ${{ always() }}
      run: |
        ls -R
        date
